"use strict";

const nodemailer = require("nodemailer");

/*
 * WELLJOB HRIS
 * New Account Credentials Mailer
 *
 * Sends a newly created user's initial credentials
 * directly to the account email address.
 *
 * IMPORTANT:
 * - The temporary password must be generated by
 *   the backend, not the Super Admin's browser.
 * - Never include the temporary password in API
 *   responses, audit descriptions, or logs.
 * - SMTP acceptance does not guarantee that an
 *   email reached the recipient's inbox.
 */

function requiredConfig(name) {
  const value = String(
    process.env[name] ?? ""
  ).trim();

  if (!value) {
    throw new Error(
      `Account email configuration missing: ${name}`
    );
  }

  return value;
}

function getMailerConfig() {
  const port = Number(
    requiredConfig("SMTP_PORT")
  );

  if (
    !Number.isInteger(port) ||
    port < 1 ||
    port > 65535
  ) {
    throw new Error(
      "Invalid SMTP_PORT."
    );
  }

  const from =
    requiredConfig("SMTP_FROM");

  if (
    /[\r\n]/.test(from)
  ) {
    throw new Error(
      "Invalid SMTP_FROM."
    );
  }

  return {
    host:
      requiredConfig("SMTP_HOST"),

    port,

    secure:
      port === 465,

    auth: {
      user:
        requiredConfig("SMTP_USER"),

      pass:
        requiredConfig("SMTP_PASSWORD"),
    },

    from,
  };
}

function validateRecipient(value) {
  if (
    typeof value !== "string"
  ) {
    throw new Error(
      "A valid account email address is required."
    );
  }

  const email =
    value.trim().toLowerCase();

  const valid =
    email.length <= 254 &&
    /^[a-z0-9._%+-]+@[a-z0-9-]+(?:\.[a-z0-9-]+)+$/.test(
      email
    ) &&
    !email
      .split("@")[1]
      .split(".")
      .some(
        (part) =>
          part.startsWith("-") ||
          part.endsWith("-")
      );

  if (!valid) {
    throw new Error(
      "A valid account email address is required."
    );
  }

  return email;
}

function requiredText(value, fieldName) {
  if (
    typeof value !== "string"
  ) {
    throw new Error(
      `${fieldName} is required.`
    );
  }

  const text =
    value.trim();

  if (
    !text ||
    /[\r\n]/.test(text)
  ) {
    throw new Error(
      `Invalid ${fieldName}.`
    );
  }

  return text;
}

function buildAccountCredentialsEmail({
  fullName,
  userId,
  username,
  role,
  assignedCompany,
  temporaryPassword,
}) {
  const lines = [
    `Hello ${fullName},`,
    "",
    "Your WELLJOB HRIS account has been created.",
    "",
    "ACCOUNT CREDENTIALS",
    `Full Name: ${fullName}`,
    `User ID: ${userId}`,
    `Username: ${username}`,
    `Role: ${role}`,
  ];

  if (assignedCompany) {
    lines.push(
      `Assigned Company: ${assignedCompany}`
    );
  }

  lines.push(
    `Temporary Password: ${temporaryPassword}`,
    "",
    "Sign in to WELLJOB HRIS using the credentials above.",
    "You will be required to change your temporary password.",
    "",
    "IMPORTANT SECURITY NOTICE",
    "Do not share your temporary password with anyone.",
    "If you were not expecting this account, contact WELLJOB IT Support immediately.",
    "",
    "After changing your password, verify your registered recovery email before using Forgot Password.",
    "",
    "WELLJOB HRIS Support"
  );

  return {
    subject:
      "WELLJOB HRIS - Your New Account Credentials",

    text:
      lines.join("\n"),
  };
}

async function sendAccountCredentials({
  to,
  fullName,
  userId,
  username,
  role,
  assignedCompany = null,
  temporaryPassword,
}) {
  const recipient =
    validateRecipient(to);

  const safeFullName =
    requiredText(
      fullName,
      "full name"
    );

  const safeUserId =
    requiredText(
      userId,
      "user ID"
    );

  const safeUsername =
    requiredText(
      username,
      "username"
    );

  const safeRole =
    requiredText(
      role,
      "role"
    );

  const safeAssignedCompany =
    assignedCompany == null
      ? null
      : requiredText(
          assignedCompany,
          "assigned company"
        );

  if (
    typeof temporaryPassword !== "string" ||
    !temporaryPassword ||
    /[\r\n]/.test(
      temporaryPassword
    )
  ) {
    throw new Error(
      "A valid temporary password is required."
    );
  }

  const config =
    getMailerConfig();

  const message =
    buildAccountCredentialsEmail({
      fullName:
        safeFullName,

      userId:
        safeUserId,

      username:
        safeUsername,

      role:
        safeRole,

      assignedCompany:
        safeAssignedCompany,

      temporaryPassword,
    });

  const transporter =
    nodemailer.createTransport({
      host:
        config.host,

      port:
        config.port,

      secure:
        config.secure,

      requireTLS:
        !config.secure,

      auth:
        config.auth,

      tls: {
        minVersion:
          "TLSv1.2",
      },
    });

  await transporter.sendMail({
    from:
      config.from,

    to:
      recipient,

    subject:
      message.subject,

    text:
      message.text,
  });
}

module.exports = {
  sendAccountCredentials,
};