import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

function countBy(employees = [], key, fallback = "Unspecified") {
  return employees.reduce((acc, emp) => {
    const value = emp?.[key] || fallback;
    acc[value] = (acc[value] || 0) + 1;
    return acc;
  }, {});
}

function toSummaryRows(summary = {}, total = 0) {
  const entries = Object.entries(summary);

  if (entries.length === 0) {
    return [["No data available", 0, "0%"]];
  }

  return entries
    .sort((a, b) => b[1] - a[1])
    .map(([label, count]) => [
      label,
      count,
      total > 0 ? `${Math.round((count / total) * 100)}%` : "0%",
    ]);
}

function getTotal(employees = [], key) {
  return employees.reduce((sum, emp) => sum + Number(emp?.[key] || 0), 0);
}

function addSectionTitle(doc, title, y) {
  doc.setFontSize(12);
  doc.setFont(undefined, "bold");
  doc.text(title, 14, y);
  doc.setFont(undefined, "normal");
}

function getNextY(doc, spacing = 10) {
  return (doc.lastAutoTable?.finalY || 40) + spacing;
}

export function exportKPIReportPDF({
  user,
  totalEmployees = 0,
  deployedEmployees = 0,
  complianceRate = 0,
  repeatOffenders = 0,
  highRiskEmployees = 0,
  goodStandingEmployees = 0,
  criticalAlerts = [],
  employees = [],
}) {
  const doc = new jsPDF();

  const generatedBy = user?.name || user?.username || "System User";
  const generatedOn = new Date().toLocaleString();

  const totalViolations = getTotal(employees, "violationCount");
  const totalSeverityScore = getTotal(employees, "severityScore");
  const totalCriticalCases = getTotal(employees, "criticalIncidentCount");
  const totalOpenCases = getTotal(employees, "openIncidentCount");

  const kpiLevelSummary = countBy(employees, "kpiLevel", "Unspecified KPI");
  const riskLevelSummary = countBy(employees, "riskLevel", "Unspecified Risk");
  const severitySummary = countBy(
    employees,
    "severityLabel",
    "Unspecified Severity"
  );
  const confidenceSummary = countBy(
    employees,
    "decisionConfidence",
    "Unspecified Confidence"
  );
  const suggestedActionSummary = countBy(
    employees,
    "suggestedHRAction",
    "Unspecified Suggested Action"
  );
  const recommendationSummary = countBy(
    employees,
    "recommendation",
    "Unspecified Recommendation"
  );

  doc.setFontSize(16);
  doc.setFont(undefined, "bold");
  doc.text("Welljob Solutions KPI Report", 14, 15);

  doc.setFontSize(10);
  doc.setFont(undefined, "normal");
  doc.text(`Generated by: ${generatedBy}`, 14, 22);
  doc.text(`Generated on: ${generatedOn}`, 14, 28);

  doc.setFontSize(9);
  doc.setTextColor(90);
  doc.text(
    "This report summarizes workforce KPI indicators without displaying individual employee names.",
    14,
    34
  );
  doc.setTextColor(0);

  addSectionTitle(doc, "KPI Summary", 42);

  autoTable(doc, {
    startY: 46,
    head: [["Metric", "Value"]],
    body: [
      ["Total Active Employees", totalEmployees],
      ["Currently Deployed Employees", deployedEmployees],
      ["Compliance Rate", `${complianceRate}%`],
      ["Good Standing Employees", goodStandingEmployees],
      ["Repeat Offenders", repeatOffenders],
      ["High Risk Employees", highRiskEmployees],
      ["Total Recorded Violations", totalViolations],
      ["Total Severity Score", totalSeverityScore],
      ["Total Critical Cases", totalCriticalCases],
      ["Total Open / Active Cases", totalOpenCases],
    ],
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [22, 163, 74] },
  });

  addSectionTitle(doc, "Critical Alerts", getNextY(doc));

  autoTable(doc, {
    startY: getNextY(doc, 4),
    head: [["Level", "Alert"]],
    body:
      criticalAlerts.length > 0
        ? criticalAlerts.map((alert) => [alert.level, alert.text])
        : [["None", "No critical alerts available"]],
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [239, 68, 68] },
  });

  addSectionTitle(doc, "KPI Level Distribution", getNextY(doc));

  autoTable(doc, {
    startY: getNextY(doc, 4),
    head: [["KPI Level", "Employees", "Percentage"]],
    body: toSummaryRows(kpiLevelSummary, totalEmployees),
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [37, 99, 235] },
  });

  addSectionTitle(doc, "Risk Level Distribution", getNextY(doc));

  autoTable(doc, {
    startY: getNextY(doc, 4),
    head: [["Risk Level", "Employees", "Percentage"]],
    body: toSummaryRows(riskLevelSummary, totalEmployees),
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [99, 102, 241] },
  });

  addSectionTitle(doc, "Severity Distribution", getNextY(doc));

  autoTable(doc, {
    startY: getNextY(doc, 4),
    head: [["Severity Level", "Employees", "Percentage"]],
    body: toSummaryRows(severitySummary, totalEmployees),
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [245, 158, 11] },
  });

  addSectionTitle(doc, "Decision Confidence Summary", getNextY(doc));

  autoTable(doc, {
    startY: getNextY(doc, 4),
    head: [["Decision Confidence", "Employees", "Percentage"]],
    body: toSummaryRows(confidenceSummary, totalEmployees),
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [124, 58, 237] },
  });

  addSectionTitle(doc, "Suggested HR Action Summary", getNextY(doc));

  autoTable(doc, {
    startY: getNextY(doc, 4),
    head: [["Suggested HR Action", "Employees", "Percentage"]],
    body: toSummaryRows(suggestedActionSummary, totalEmployees),
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [14, 165, 233] },
  });

  addSectionTitle(doc, "System Recommendation Summary", getNextY(doc));

  autoTable(doc, {
    startY: getNextY(doc, 4),
    head: [["System Recommendation", "Employees", "Percentage"]],
    body: toSummaryRows(recommendationSummary, totalEmployees),
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [16, 185, 129] },
  });

  const finalY = getNextY(doc, 8);

  if (finalY > 265) {
    doc.addPage();
    doc.setFontSize(9);
    doc.setTextColor(90);
    doc.text(
      "Decision-support reminder: System-generated KPI outputs are intended to assist HR review and do not replace final HR judgment.",
      14,
      20
    );
  } else {
    doc.setFontSize(9);
    doc.setTextColor(90);
    doc.text(
      "Decision-support reminder: System-generated KPI outputs are intended to assist HR review and do not replace final HR judgment.",
      14,
      finalY
    );
  }

  doc.save("Welljob_KPI_Report.pdf");
}