import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function exportKPIReportPDF({
  user,
  totalEmployees,
  deployedEmployees,
  complianceRate,
  repeatOffenders,
  highRiskEmployees,
  criticalAlerts,
  employees,
}) {
  const doc = new jsPDF();

  doc.setFontSize(16);
  doc.text("Welljob Solutions KPI Report", 14, 15);

  doc.setFontSize(10);
  doc.text(
    `Generated by: ${user?.name || user?.username || "System User"}`,
    14,
    22
  );
  doc.text(`Generated on: ${new Date().toLocaleString()}`, 14, 28);

  doc.setFontSize(12);
  doc.text("KPI Summary", 14, 38);

  autoTable(doc, {
    startY: 42,
    head: [["Metric", "Value"]],
    body: [
      ["Total Active Employees", totalEmployees],
      ["Currently Deployed Employees", deployedEmployees],
      ["Compliance Rate", `${complianceRate}%`],
      ["Repeat Offenders", repeatOffenders],
      ["High Risk Employees", highRiskEmployees],
    ],
    styles: { fontSize: 10 },
    headStyles: { fillColor: [22, 163, 74] },
  });

  doc.text("Critical Alerts", 14, doc.lastAutoTable.finalY + 10);

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 14,
    head: [["Level", "Alert"]],
    body: criticalAlerts.map((alert) => [alert.level, alert.text]),
    styles: { fontSize: 10 },
    headStyles: { fillColor: [239, 68, 68] },
  });

  doc.text("Employee Risk Table", 14, doc.lastAutoTable.finalY + 10);

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 14,
    head: [
      [
        "Employee",
        "Company",
        "Status",
        "Violations",
        "Severity Score",
        "KPI Level",
        "Risk Level",
        "Recommendation",
        "Reason",
      ],
    ],
    body: employees.map((emp) => [
      emp.name,
      emp.company,
      emp.status,
      emp.violationCount,
      emp.severityScore,
      emp.kpiLevel,
      emp.riskLevel,
      emp.recommendation,
      emp.recommendationReason,
    ]),
    styles: { fontSize: 9 },
    headStyles: { fillColor: [37, 99, 235] },
  });

  doc.save("Welljob_KPI_Report.pdf");
}