export const PERMISSIONS = {
  // Operational actions
  CAN_ADD_EMPLOYEE: "CAN_ADD_EMPLOYEE",
  CAN_EDIT_EMPLOYEE: "CAN_EDIT_EMPLOYEE",
  CAN_DELETE_EMPLOYEE: "CAN_DELETE_EMPLOYEE",
  CAN_ADD_INCIDENT: "CAN_ADD_INCIDENT",
  CAN_EDIT_INCIDENT: "CAN_EDIT_INCIDENT",
  CAN_EXPORT_PDF: "CAN_EXPORT_PDF",
  // System/Admin actions
  CAN_MAINTAIN_IT_USERS: "CAN_MAINTAIN_IT_USERS"
};