export const PERMISSIONS = {
  CAN_ADD_EMPLOYEE: "CAN_ADD_EMPLOYEE",
  CAN_EDIT_EMPLOYEE: "CAN_EDIT_EMPLOYEE",
  CAN_ARCHIVE_EMPLOYEE: "CAN_ARCHIVE_EMPLOYEE",
  CAN_VIEW_ARCHIVED_EMPLOYEES: "CAN_VIEW_ARCHIVED_EMPLOYEES",
  CAN_RESTORE_ARCHIVED_EMPLOYEES: "CAN_RESTORE_ARCHIVED_EMPLOYEES",
  CAN_ADD_INCIDENT: "CAN_ADD_INCIDENT",
  CAN_EDIT_INCIDENT: "CAN_EDIT_INCIDENT",
  CAN_EXPORT_PDF: "CAN_EXPORT_PDF",
  CAN_MAINTAIN_IT_USERS: "CAN_MAINTAIN_IT_USERS",
  CAN_CREATE_SYSTEM_USERS: "CAN_CREATE_SYSTEM_USERS",
  CAN_CONFIGURE_KPI_RULES: "CAN_CONFIGURE_KPI_RULES",
};