import { ROLES } from "./roles";
import { PERMISSIONS } from "./permissions";

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: [
    PERMISSIONS.CAN_CREATE_SYSTEM_USERS,
    PERMISSIONS.CAN_CONFIGURE_KPI_RULES,
  ],

  [ROLES.HR_MANAGER]: [
    PERMISSIONS.CAN_EXPORT_PDF,

    PERMISSIONS.CAN_ADD_EMPLOYEE,
    PERMISSIONS.CAN_EDIT_EMPLOYEE,

    PERMISSIONS.CAN_ADD_INCIDENT,
    PERMISSIONS.CAN_EDIT_INCIDENT,

    PERMISSIONS.CAN_CONFIGURE_KPI_RULES,
  ],

  [ROLES.HR_STAFF]: [
    PERMISSIONS.CAN_ADD_EMPLOYEE,
    PERMISSIONS.CAN_EDIT_EMPLOYEE,

    PERMISSIONS.CAN_ADD_INCIDENT,
    PERMISSIONS.CAN_EDIT_INCIDENT,
  ],

  [ROLES.IT_SUPPORT]: [
    PERMISSIONS.CAN_MAINTAIN_IT_USERS,
  ],
};