/*
 * WELLJOB SOLUTIONS
 * Migration #12: Forgot Password approval requests
 *
 * Creates a request queue for approval-based password recovery.
 *
 * IMPORTANT:
 * - This migration does not alter existing users or passwords.
 * - Raw passwords and reset tokens must never be stored here.
 * - Do not edit this file after the migration has been applied
 *   and recorded in schema_migrations.
 */

CREATE TABLE password_reset_requests (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,

  /*
   * users.id is a signed INT in the existing database.
   * Keep this foreign-key column compatible with it.
   */
  user_id INT NOT NULL,

  /*
   * Captures the account's token_version when the request
   * is created. Approval must reject a request if this
   * version no longer matches the current account.
   */
  requested_token_version INT UNSIGNED NOT NULL,

  status ENUM(
    'PENDING',
    'SENDING',
    'SENT',
    'REJECTED',
    'EXPIRED',
    'SEND_FAILED',
    'CANCELLED'
  ) NOT NULL DEFAULT 'PENDING',

  requested_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  expires_at DATETIME NOT NULL,

  /*
   * The authorized reviewer who made the decision.
   * Self-approval will be prevented by backend authorization.
   */
  reviewed_by_user_id INT NULL,

  reviewed_at DATETIME NULL,

  /*
   * Records the approved identity-verification method,
   * without storing identity documents or sensitive answers.
   */
  identity_verification_method VARCHAR(32)
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_general_ci
    NULL,

  identity_verified_at DATETIME NULL,

  sent_at DATETIME NULL,

  delivery_failed_at DATETIME NULL,

  updated_at TIMESTAMP NOT NULL
    DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (id),

  KEY idx_password_reset_requests_user_status (
    user_id,
    status,
    requested_at
  ),

  KEY idx_password_reset_requests_status_expiry (
    status,
    expires_at,
    requested_at
  ),

  KEY idx_password_reset_requests_reviewer (
    reviewed_by_user_id,
    reviewed_at
  ),

  CONSTRAINT fk_password_reset_requests_user
    FOREIGN KEY (user_id)
    REFERENCES users (id)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT,

  CONSTRAINT fk_password_reset_requests_reviewer
    FOREIGN KEY (reviewed_by_user_id)
    REFERENCES users (id)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;