import {
  FiBarChart2,
  FiBriefcase,
  FiCheckCircle,
  FiClipboard,
  FiFileText,
  FiMessageSquare,
  FiRefreshCw,
  FiShield,
  FiTarget,
  FiUser,
  FiUsers,
  FiVideo,
  FiZap,
} from "react-icons/fi";

import Button from "../../ui/Button";
import Dialog from "../../ui/Dialog";

import KPIBadge from "../badges/KPIBadge";
import RiskBadge from "../badges/RiskBadge";

import {
  DECISION_CONFIDENCE,
  HR_ACTION_WORKFLOW,
  WELLJOB_LOW_KPI_ACTIONS,
  getDecisionConfidenceClasses,
  getSuggestedHRActionClasses,
} from "../../../utils/kpi/kpiHelpers";

function formatEmployeeId(id) {
  return String(id || "-").replace(/^KPI-/i, "");
}

function getDisplayValue(value) {
  if (value === 0) {
    return 0;
  }

  if (
    value === null ||
    value === undefined ||
    value === ""
  ) {
    return "-";
  }

  return value;
}

function getInitials(name) {
  return String(name || "Employee")
    .split(" ")
    .filter(Boolean)
    .slice(0, 2)
    .map((part) =>
      part[0]?.toUpperCase()
    )
    .join("");
}

function CompactInfo({
  icon,
  label,
  value,
}) {
  return (
    <div className="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 dark:border-slate-800 dark:bg-slate-950/40">
      <div className="flex items-center gap-2 text-[11px] font-black uppercase tracking-wide text-slate-500 dark:text-slate-400">
        {icon}
        {label}
      </div>

      <p className="mt-1 truncate text-sm font-black text-slate-900 dark:text-white">
        {getDisplayValue(value)}
      </p>
    </div>
  );
}

function DecisionBadge({
  icon,
  label,
  className,
}) {
  return (
    <span
      className={[
        "inline-flex max-w-full items-center gap-1.5 rounded-full border px-2.5 py-1",
        "text-[11px] font-black leading-5",
        className,
      ].join(" ")}
      title={label}
    >
      {icon}

      <span className="truncate">
        {label}
      </span>
    </span>
  );
}

function DecisionExplanationPanel({
  decisionBasis,
  confidenceReason,
  suggestedStepReason,
}) {
  return (
    <section className="rounded-3xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-800 dark:bg-slate-950/30">
      <div className="mb-4">
        <h3 className="flex items-center gap-2 text-sm font-black text-slate-900 dark:text-white">
          <FiClipboard
            className="text-indigo-500 dark:text-indigo-300"
            aria-hidden="true"
          />

          Decision Explanation
        </h3>

        <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">
          Explains the basis, confidence level,
          and suggested HR step generated by the
          system.
        </p>
      </div>

      <div className="space-y-3">
        <div className="rounded-2xl border border-indigo-200 bg-indigo-50 p-4 dark:border-indigo-900/60 dark:bg-indigo-950/20">
          <p className="text-[11px] font-black uppercase tracking-wide text-indigo-700 dark:text-indigo-300">
            Main Decision Basis
          </p>

          <p className="mt-2 text-sm leading-6 text-indigo-700/90 dark:text-indigo-200/90">
            {decisionBasis}
          </p>
        </div>

        <div className="grid gap-3 lg:grid-cols-2">
          <div className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900">
            <p className="flex items-center gap-2 text-[11px] font-black uppercase tracking-wide text-slate-500 dark:text-slate-400">
              <FiZap aria-hidden="true" />
              Confidence Reason
            </p>

            <p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">
              {confidenceReason}
            </p>
          </div>

          <div className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900">
            <p className="flex items-center gap-2 text-[11px] font-black uppercase tracking-wide text-slate-500 dark:text-slate-400">
              <FiShield aria-hidden="true" />
              Suggested Step Reason
            </p>

            <p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">
              {suggestedStepReason}
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}

function getActionIcon(code) {
  switch (code) {
    case "VERBAL_COUNSELING":
      return (
        <FiMessageSquare aria-hidden="true" />
      );

    case "PERFORMANCE_IMPROVEMENT_PLAN":
      return (
        <FiTarget aria-hidden="true" />
      );

    case "REASSIGNMENT_OF_POSITION":
      return (
        <FiRefreshCw aria-hidden="true" />
      );

    case "SEMINAR_WEBINAR":
      return (
        <FiVideo aria-hidden="true" />
      );

    case "EMPLOYEE_TRAINING":
      return (
        <FiUsers aria-hidden="true" />
      );

    default:
      return (
        <FiShield aria-hidden="true" />
      );
  }
}

function ActionChip({
  action,
  isRecommended = false,
}) {
  return (
    <div
      className={[
        "rounded-2xl border px-3 py-2",
        isRecommended
          ? "border-amber-400 bg-amber-50 text-amber-800 dark:border-amber-700 dark:bg-amber-950/30 dark:text-amber-300"
          : "border-slate-200 bg-white text-slate-600 dark:border-slate-800 dark:bg-slate-950/30 dark:text-slate-300",
      ].join(" ")}
    >
      <div className="flex items-center gap-2">
        <span className="text-sm">
          {getActionIcon(action.code)}
        </span>

        <p className="truncate text-xs font-black">
          {action.title}
        </p>

        {isRecommended && (
          <span className="ml-auto rounded-full bg-amber-200 px-2 py-0.5 text-[9px] font-black uppercase text-amber-900 dark:bg-amber-900 dark:text-amber-200">
            Suggested
          </span>
        )}
      </div>
    </div>
  );
}

export default function EmployeeKpiDetailsModal({
  employee,
  onClose,
}) {
  const isOpen = Boolean(employee);

  const recommendation =
    employee?.recommendation ||
    "Retain / Maintain Good Standing";

  const correctiveActionCode =
    employee?.correctiveActionCode ||
    "RETAIN";

  const isRetain =
    correctiveActionCode === "RETAIN" ||
    recommendation === "Retain" ||
    recommendation ===
      "Retain / Maintain Good Standing";

  const decisionConfidence =
    employee?.decisionConfidence ||
    DECISION_CONFIDENCE.LOW;

  const suggestedHRAction =
    employee?.suggestedHRAction ||
    HR_ACTION_WORKFLOW.MONITOR;

  const decisionConfidenceReason =
    employee?.decisionConfidenceReason ||
    "Decision confidence is based on incident count, severity score, critical cases, and risk level.";

  const suggestedHRActionReason =
    employee?.suggestedHRActionReason ||
    "Suggested HR action is generated from the employee KPI evaluation and still requires HR validation.";

  const recommendationReason =
    employee?.correctiveActionReason ||
    employee?.recommendationReason ||
    "No recommendation reason available.";

  const correctiveActionBasis =
    employee?.correctiveActionBasis ||
    "Based on KPI level, violation count, severity score, and risk level.";

  const employeeName =
    employee?.name ||
    "Unknown Employee";

  const employeeCompany =
    employee?.company ||
    "Unassigned";

  return (
    <Dialog
      open={isOpen}
      onClose={onClose}
      title={employeeName}
      description={
        employee
          ? `Employee ID: ${formatEmployeeId(
              employee.id
            )} • ${employeeCompany}`
          : "Employee KPI decision-support details"
      }
      size="xl"
      tone="default"
      footer={
        <Button
          type="button"
          variant="secondary"
          onClick={onClose}
        >
          Close
        </Button>
      }
    >
      {employee && (
        <div className="space-y-5">
          <section className="flex items-center gap-3 rounded-2xl border border-indigo-200 bg-indigo-50 p-4 dark:border-indigo-900/60 dark:bg-indigo-950/20">
            <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-indigo-100 text-sm font-black text-indigo-700 dark:bg-indigo-950/60 dark:text-indigo-300">
              {getInitials(employeeName)}
            </div>

            <div className="min-w-0">
              <p className="truncate font-black text-slate-900 dark:text-white">
                {employeeName}
              </p>

              <p className="mt-0.5 text-xs font-semibold text-slate-500 dark:text-slate-400">
                System-generated KPI evaluation
                and HR decision-support summary
              </p>
            </div>
          </section>

          <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            <CompactInfo
              icon={
                <FiBriefcase aria-hidden="true" />
              }
              label="Company"
              value={employeeCompany}
            />

            <CompactInfo
              icon={<FiUser aria-hidden="true" />}
              label="Status"
              value={
                employee.status ||
                "Unknown"
              }
            />

            <CompactInfo
              icon={
                <FiFileText aria-hidden="true" />
              }
              label="Violations"
              value={
                employee.violationCount ??
                0
              }
            />

            <CompactInfo
              icon={
                <FiBarChart2 aria-hidden="true" />
              }
              label="Severity Score"
              value={
                employee.severityScore ??
                0
              }
            />
          </section>

          <section className="rounded-3xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-950/30">
            <div className="mb-3">
              <h3 className="text-sm font-black text-slate-900 dark:text-white">
                KPI Decision Summary
              </h3>

              <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">
                System-generated evaluation for
                authorized HR review.
              </p>
            </div>

            <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
              <div className="rounded-2xl border border-slate-200 bg-slate-50 p-3 dark:border-slate-800 dark:bg-slate-900">
                <p className="mb-2 text-[11px] font-black uppercase tracking-wide text-slate-500 dark:text-slate-400">
                  KPI Level
                </p>

                <KPIBadge
                  level={
                    employee.kpiLevel ||
                    "Good Standing"
                  }
                />
              </div>

              <div className="rounded-2xl border border-slate-200 bg-slate-50 p-3 dark:border-slate-800 dark:bg-slate-900">
                <p className="mb-2 text-[11px] font-black uppercase tracking-wide text-slate-500 dark:text-slate-400">
                  Risk Level
                </p>

                <RiskBadge
                  level={
                    employee.riskLevel ||
                    "Low Risk"
                  }
                />
              </div>

              <div className="rounded-2xl border border-slate-200 bg-slate-50 p-3 dark:border-slate-800 dark:bg-slate-900">
                <p className="mb-2 text-[11px] font-black uppercase tracking-wide text-slate-500 dark:text-slate-400">
                  Confidence
                </p>

                <DecisionBadge
                  icon={
                    <FiZap
                      size={12}
                      aria-hidden="true"
                    />
                  }
                  label={decisionConfidence}
                  className={getDecisionConfidenceClasses(
                    decisionConfidence
                  )}
                />
              </div>

              <div className="rounded-2xl border border-slate-200 bg-slate-50 p-3 dark:border-slate-800 dark:bg-slate-900">
                <p className="mb-2 text-[11px] font-black uppercase tracking-wide text-slate-500 dark:text-slate-400">
                  Suggested Step
                </p>

                <DecisionBadge
                  icon={
                    <FiShield
                      size={12}
                      aria-hidden="true"
                    />
                  }
                  label={suggestedHRAction}
                  className={getSuggestedHRActionClasses(
                    suggestedHRAction
                  )}
                />
              </div>
            </div>
          </section>

          <section
            className={[
              "rounded-3xl border p-4",
              isRetain
                ? "border-emerald-200 bg-emerald-50 text-emerald-800 dark:border-emerald-900/60 dark:bg-emerald-950/20 dark:text-emerald-300"
                : "border-amber-200 bg-amber-50 text-amber-800 dark:border-amber-900/60 dark:bg-amber-950/20 dark:text-amber-300",
            ].join(" ")}
          >
            <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between">
              <div>
                <p className="text-[11px] font-black uppercase tracking-wide opacity-80">
                  Recommended HR Action
                </p>

                <div className="mt-2 flex flex-wrap items-center gap-2 text-sm font-black">
                  {isRetain ? (
                    <FiCheckCircle aria-hidden="true" />
                  ) : (
                    <FiShield aria-hidden="true" />
                  )}

                  {recommendation}
                </div>
              </div>

              <span className="w-fit rounded-full bg-white/60 px-3 py-1 text-[10px] font-black uppercase dark:bg-slate-950/30">
                System suggestion
              </span>
            </div>

            <p className="mt-3 text-sm leading-6">
              {recommendationReason}
            </p>
          </section>

          <DecisionExplanationPanel
            decisionBasis={
              correctiveActionBasis
            }
            confidenceReason={
              decisionConfidenceReason
            }
            suggestedStepReason={
              suggestedHRActionReason
            }
          />

          {!isRetain && (
            <section className="rounded-3xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-800 dark:bg-slate-950/30">
              <div className="mb-3">
                <h3 className="text-sm font-black text-slate-900 dark:text-white">
                  Corrective Action Guide
                </h3>

                <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">
                  The suggested action is
                  highlighted for HR reference.
                </p>
              </div>

              <div className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">
                {WELLJOB_LOW_KPI_ACTIONS.map(
                  (action) => (
                    <ActionChip
                      key={action.code}
                      action={action}
                      isRecommended={
                        action.code ===
                        correctiveActionCode
                      }
                    />
                  )
                )}
              </div>
            </section>
          )}

          <section className="rounded-2xl border border-indigo-200 bg-indigo-50 p-4 text-sm leading-6 text-indigo-700 dark:border-indigo-900/60 dark:bg-indigo-950/20 dark:text-indigo-300">
            <div className="mb-1 flex items-center gap-2 font-black">
              <FiClipboard aria-hidden="true" />
              Decision-support reminder
            </div>

            <p className="text-xs leading-5">
              The system recommends and explains
              the action, but the HR Manager
              remains responsible for the final
              decision.
            </p>
          </section>
        </div>
      )}
    </Dialog>
  );
}